apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  selector:
    app: todo-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 3040
      nodePort: 31110
  type: NodePort
